language: node_js
node_js:
  - "0.11"
before_install:
  - "export COMMIT_SHA=`git log -1 --pretty=format:%H`"
script:
  - gulp build
  - gulp publish-s3
env:
  global:
    secure: CzF6TS2ifMVu3qDRtxSUwTyWyw6apiHH8MGRI0WazNCQ9zGw2j1eNogFYETAAuD8tKstHkriNVWomV10e+Bpv09FZlSESJmcYXDu8AXpfwADykvQBhmkOjrhBjEONK02iLv8sgCAdRj86hwL7dLC99XMmc4Ch55bBZtf0ZM/Aw8=
